---
title: "Week 10 - 1"
author: "Sandeep Joshi"
date: "July 22, 2019"
output:
  pdf_document: default
---

## K-means Cluster Analysis

```{r}
install.packages("factoextra")
library(tidyverse)  # data manipulation
library(cluster)    # clustering algorithms
library(factoextra) # clustering algorithms & visualization
```

```{r}
df <- USArrests
# remove missing data
df <- na.omit(df)
# Scaling/ standardizing the data
df <- scale(df)
head(df)

# Clustering Distance Measures, defaults to Eucledian
distance <- get_dist(df)
# Visualizing a distance matrix
fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
```

## Computing k-means clustering in R
```{r}
k2 <- kmeans(df, centers = 2, nstart = 25)
str(k2)

# K-mean clustering
k2
# Graphical representations
fviz_cluster(k2, data = df)

# Standard pairwise scatter plots.
df %>%
  as_tibble() %>%
  mutate(cluster = k2$cluster,
         state = row.names(USArrests)) %>%
  ggplot(aes(UrbanPop, Murder, color = factor(cluster), label = state)) +
  geom_text()
```


## Rest of the clusters
```{r}
k3 <- kmeans(df, centers = 3, nstart = 25)
k4 <- kmeans(df, centers = 4, nstart = 25)
k5 <- kmeans(df, centers = 5, nstart = 25)
# Plots to compare
p1 <- fviz_cluster(k2, geom = "point", data = df) + ggtitle("k = 2")
p2 <- fviz_cluster(k3, geom = "point",  data = df) + ggtitle("k = 3")
p3 <- fviz_cluster(k4, geom = "point",  data = df) + ggtitle("k = 4")
p4 <- fviz_cluster(k5, geom = "point",  data = df) + ggtitle("k = 5")

library(gridExtra)
grid.arrange(p1, p2, p3, p4, nrow = 2)
```


## Elbow Method for optimal clustering
```{r}
set.seed(123) # seed is used so we can work with same data again.
# function to compute total within-cluster sum of square 
wss <- function(k) {
  kmeans(df, k, nstart = 10 )$tot.withinss
}

# Compute and plot wss for k = 1 to k = 15
k.values <- 1:15

# extract wss for 2-15 clusters
wss_values <- map_dbl(k.values, wss)
plot(k.values, wss_values,
       type="b", pch = 19, frame = FALSE, 
       xlab="Number of clusters K",
       ylab="Total within-clusters sum of squares")

# Shortcut method for doing above
set.seed(123)
fviz_nbclust(df, kmeans, method = "wss")
```


## Average Silhouette Method for optimal clustering
```{r}
# function to compute average silhouette for k clusters
avg_sil <- function(k) {
  km.res <- kmeans(df, centers = k, nstart = 25)
  ss <- silhouette(km.res$cluster, dist(df))
  mean(ss[, 3])
}

# Compute and plot wss for k = 2 to k = 15
k.values <- 2:15

# extract avg silhouette for 2-15 clusters
avg_sil_values <- map_dbl(k.values, avg_sil)

plot(k.values, avg_sil_values,
       type = "b", pch = 19, frame = FALSE, 
       xlab = "Number of clusters K",
       ylab = "Average Silhouettes")

# Shortcut method for doing above
fviz_nbclust(df, kmeans, method = "silhouette")
```

## Gap Statistic Method for optimal clustering
```{r}
# compute gap statistic
set.seed(123)
gap_stat <- clusGap(df, FUN = kmeans, nstart = 25,
                    K.max = 10, B = 50)
# Print the result
print(gap_stat, method = "firstmax")

# Shortcut method for doing above
fviz_gap_stat(gap_stat)
```


## Extracting result
```{r}
# Compute k-means clustering with k = 4
set.seed(123)
final <- kmeans(df, 4, nstart = 25)
print(final)

# Visualizing it
fviz_cluster(final, data = df)

# Extracting clusters
USArrests %>%
  mutate(Cluster = final$cluster) %>%
  group_by(Cluster) %>%
  summarise_all("mean")
```