---
title: "Week 10 -3"
author: "Sandeep Joshi"
date: "July 27, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## K-Means Clustering
```{r}
set.seed(1234) # setting seed for confirming repeatabity of data
x <- rnorm(12, mean = rep(1:3, each = 4), sd = 0.2)
y <- rnorm(12, mean = rep(c(1, 2, 1), each = 4), sd = 0.2)

# scatterplot for random data
plot(x, y, col = "blue", pch = 19, cex = 2) 
text(x + 0.05, y + 0.05, labels = as.character(1:12))
```

## Using the kmeans() function and choosing 3 centroids
```{r}
dataFrame <- data.frame(x, y)
kmeansObj <- kmeans(dataFrame, centers = 3)
names(kmeansObj)

# Clusters:
kmeansObj$cluster
```

## Replotting above using new centroids:
```{r}
par(mar = rep(0.2, 4))
plot(x, y, col = kmeansObj$cluster, pch = 19, cex = 2)
points(kmeansObj$centers, col = 1:3, pch = 3, cex = 3, lwd =3)
```


## Building heatmaps from K-means solutions
```{r}
set.seed(1234)
dataMatrix <- as.matrix(dataFrame)[sample(1:12), ]
kmeansObj <- kmeans(dataMatrix, centers = 3)

# Getting images for heatmap plots
par(mfrow = c(1, 2))
image(t(dataMatrix)[, nrow(dataMatrix):1], yaxt = "n", main = "Original Data")
image(t(dataMatrix)[, order(kmeansObj$cluster)], yaxt = "n", main = "Clustered Data")
```


