---
title: "Plotting systems and Graphic Devices"
author: "Sandeep Joshi"
date: "July 22, 2019"
output:
  pdf_document: default
---

## 7.1 The Base Plotting System
```{r}
#install packages required
install.packages("ggplot2")
install.packages("lattice")
#Scatterplot with loess curve
data(airquality)
with(airquality, plot(airquality$Temp, airquality$Ozone))
lines(loess.smooth(airquality$Temp, airquality$Ozone))
```

```{r}
data(cars)
## Create the plot / draw canvas
with(cars, plot(speed, dist))
## Add annotation
title("Speed vs. Stopping distance")
```

## 7.2 The Lattice System
```{r}
library(lattice)
state <- data.frame(state.x77, region = state.region)
xyplot(Life.Exp ~ Income | region, data = state, layout = c(4, 1))
```

## 7.3 The ggplot2 System
```{r}
#gplot2 functions are similar to lattice, but the system is generally easier and more intuitive to use.
library(ggplot2)
data(mpg)
qplot(displ, hwy, data = mpg)
```


##8 Graphics Devices

## 8.1 The Process of Making a Plot
```{r}
library(datasets)
 
## Create plot on screen device
with(faithful, plot(eruptions, waiting))  
 
## Annotate with a title
title(main = "Old Faithful Geyser data")  
 
## Open PDF device; create 'myplot.pdf' in my working directory
pdf(file = "myplot.pdf")  

## Create plot and send to a file (no plot appears on screen)
with(faithful, plot(eruptions, waiting))  

## Annotate plot; still nothing on screen
title(main = "Old Faithful Geyser data")  

## Close the PDF file device
dev.off()  
```
## 8.5 Copying Plots
## Copy my plot to a PNG file
```{r}
## Create plot on screen device
with(faithful, plot(eruptions, waiting))  

## Add a main title
title(main = "Old Faithful Geyser data")  

## Copy my plot to a PNG file
dev.copy(png, file = "geyserplot.png")  
 
## Don't forget to close the PNG device!
dev.off()  
```